### ISSUE TITLE
Multiple Multiplayer Windows

### ISSUE THREAD

**Issue by Chik3r** [software-inc-multiplayer/software-inc-multiplayer#11]
**Describe the bug**
If you click multiple times the multiplayer button, it creates multiple windows.

**To Reproduce**
1. Install 0.2.0-unstable
2. Enable mod
3. Click on 'Multiplayer' multiple times
4. See error (Move the windows to see that there's more than one window)

**Expected behaviour**
Only create 1 window.

**Screenshots**
![alt text](https://i.imgur.com/U70rkoa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Alpha 11.6.11

**Comment by Chik3r** [comment]
Also, the game freezes a little when clicking the 'Multiplayer' button.

**Comment by ghost** [comment]
You need to press "Server Info" for the tab to show
This is how Multi-Tab windows show.

It will freeze a little the first time because it doesn't have your IP to show in the server info tab.

**Comment by ghost** [comment]
Will definitlely think about caching the IP in a setting.

**Comment by ghost** [comment]
Oh, im so dumb, i did not see that there were two windows.

My bad!

**Comment by ghost** [comment]
This is an easy fix, will be fixed in the next unstable version.
