### ISSUE TITLE
Multiplayer menu can become unopenable

### ISSUE THREAD

**Issue by MattA-Official** [software-inc-multiplayer/software-inc-multiplayer#12]
**Describe the bug**
When the multiplayer menu is open and you go to a different screen and then return to the main one the multiplayer window will close and you can't open it back up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the "Multiplayer menu" (button on the main screen)
2. Click on "New Game"
3. Click on "Cancel"
4. Try to open the "Multiplayer menu" (button on the main screen)
5. See that it doesn't work and makes an error sound

**Expected behaviour**
The multiplayer menu should open back up when you click on the button.

**Desktop (please complete the following information):**
 - OS: Windows 10 ()
 - Software Inc Version: Alpha 11.6.11
 - Mod Version: 0.2.1

**Comment by daredloco** [comment]
I did fix the bug by changing 

```cs
private void SceneChanged(Scene scene, LoadSceneMode mode)
        {
            if (scene.name != "MainMenu") return;
            CreateButton();
        }
```

to 

```cs
private void SceneChanged(Scene scene, LoadSceneMode mode)
        {
            if (scene.name != "MainMenu")
            {
                isWindowUp = false;
                return;
            }
            CreateButton();
        }
```
