### ISSUE TITLE
Have the mod version on the multiplayer options screen.

### ISSUE THREAD

**Issue by MattA-Official** [software-inc-multiplayer/software-inc-multiplayer#13]
#### Describe the feature you'd like

The multiplayer options screen should show the mod version. 

#### Benefits of this:

1. People can make sure they are using the correct mod version to connect to a server (in case of incompatibilities)
2. People can easily find their mod version to put in bug reports.
3. It will make me happy.

**Comment by ghost** [comment]
This will definitely be added as a separate tab.
