### ISSUE TITLE
Installer error when Alt-tabbing

### ISSUE THREAD

**Issue by Chik3r** [software-inc-multiplayer/software-inc-multiplayer#15]
**Describe the bug**
If you open the version dropdown and ALT-TAB, the installer throws an error.

**To Reproduce**
1. Open installer.
2. Open the version dropdown (but don't select anything)
3. ALT-TAB to another application

**Expected behaviour**
The installer shouldn't give an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/31808958/90030530-27d3a200-dc8a-11ea-831a-9a3517caa8bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Alpha 11.6.11
 - Mod Version: Installer
 
**Additional context**
Crash: [https://pastebin.com/BWsNCRSB](https://pastebin.com/BWsNCRSB)

**Comment by cal3432** [comment]
Can you show the details?

**Comment by ghost** [comment]
Alt-Tab is a shortcut for deselecting the list, this is probably because I didn't check if it was null before getting the value etc.
