### ISSUE TITLE
multiple multiplayer buttons

### ISSUE THREAD

**Issue by DankPoutart** [software-inc-multiplayer/software-inc-multiplayer#17]
**Describe the bug**
When i disable the mod and enable it again right after each other i get an error message (screenshot) and another multiplayer button. if i do it more times i keep getting more multiplayer buttons.

**To Reproduce**
1. Go to options, mods and enable the multiplayer mod
2. spam click the box to enable and disable the mod
3. you get an error message and a second multiplayer button

**Expected behaviour**
shouldnt give any error and not give a second button

**Screenshots**
![image](https://user-images.githubusercontent.com/69596571/90043622-a2251600-dccc-11ea-9d5a-951711b8e729.png)
![image](https://user-images.githubusercontent.com/69596571/90043713-c4b72f00-dccc-11ea-95ac-b8f952c5a7f1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version 11.16.11
 - Mod Version 0.2.2 unstable

**Comment by ghost** [comment]
First of all, you're not meant to spam click, I might make it so you can't disable the mod or something when you enable it.

This is expected behaviour and is self bugged.
