### ISSUE TITLE
Version dropdown broken

### ISSUE THREAD

**Issue by MattA-Official** [software-inc-multiplayer/software-inc-multiplayer#2]
**Describe the bug**
If you select latest (the only option) and press install it won't work.

**To Reproduce**
1. Go to 'Version dropdown'
2. Click on 'latest'
3. Press install

**Expected behaviour**
The thing should install using the latest version of Software Inc.

**Screenshots**
![image](https://user-images.githubusercontent.com/43476212/89741161-e7f09d00-da86-11ea-8ee3-3033ec728d2b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Latest

**Comment by Datsami000** [comment]
Essentially, Oh shit.

**Comment by ghost** [comment]
Working on it now. May be an error in octokit.

**Comment by Datsami000** [comment]
Hooray.

**Comment by ghost** [comment]
Fixed in Installer v1.0.1
