### ISSUE TITLE
Disabling the mod doesn't remove all commands.

### ISSUE THREAD

**Issue by Chik3r** [software-inc-multiplayer/software-inc-multiplayer#20]
**Describe the bug**
When you disable or reload the mod, 2 commands (`MULTIPLAYER_USERS` and `MULTIPLAYER_GAMEWORLD`) are not removed.

**To Reproduce**
1. Enable mod
2. Disable mod
3. Open console and type `MULTIPLAYER_USERS` or `MULTIPLAYER_GAMEWORLD`

**Expected behaviour**
The commands should be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/31808958/90287384-c2c4ab80-de45-11ea-8d88-235f4b3c289e.png)
![image](https://user-images.githubusercontent.com/31808958/90287547-13d49f80-de46-11ea-8841-e957ac62faa8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: 11.6.11
 - Mod Version: v0.2.4-unstable
 
**Additional context**
:)

**Comment by Chik3r** [comment]
I think to fix this all you have to do is add:
```
DevConsole.Console.RemoveCommand("MULTIPLAYER_USERS");
DevConsole.Console.RemoveCommand("MULTIPLAYER_GAMEWORLD");
```
to the `OnDeactivate()` function in [DebugConsole.cs](https://github.com/cal3432/software-inc-multiplayer/blob/nightly/swinc.multiplayer/Multiplayer.Core/DebugConsole.cs)

**Comment by daredloco** [comment]
Damn I had this in a version but did override it and forgot about it...
Thanks for the hint, is fixed and on the nightly now
