### ISSUE TITLE
Make the "you started a server" thing more visible.

### ISSUE THREAD

**Issue by Datsami000** [software-inc-multiplayer/software-inc-multiplayer#3]
It is hard to see, so when any save file is entered, display a message that says, "A Multiplayer Server is being hosted on your PC" to let the user know that thier PC is a server for SWinc.

**Comment by ghost** [comment]
I'll work on it.

**Comment by ghost** [comment]
Will be implemented in v0.1.0-closed

**Comment by Datsami000** [comment]
It wasn't implemented :(

**Comment by ghost** [comment]
It was removed as it was causing peformance issues. (The multiplayer button on the main menu lagging, quick freeze after mod enabled)

**Comment by Datsami000** [comment]
oof

**Comment by Datsami000** [comment]
Hey, it was re-added in 0.3.1! Nice!
