### ISSUE TITLE
Ingame button keeps showing up even if mod was deactivated

### ISSUE THREAD

**Issue by daredloco** [software-inc-multiplayer/software-inc-multiplayer#30]
**Describe the bug**
Ingame button keeps showing up even if mod was deactivated

**To Reproduce**
1. Start SINC
2. Deactivate mod
3. (Get error "can't activate mod")
4. Start game (new, load or continue)
5. Button appears on the top

**Expected behaviour**
Button not shown if mod is deactivated

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Software Inc Version 11.6.11
 - Mod Version 0.2.6-unstable
 
**Additional context**
Try to add this before adding the button:
```cs
if(isActiveAndEnabled)
```

strange but this did happen only when the 'cant activate mod' error came up...

**Comment by ghost** [comment]
Reason: Forgot to remove the event handler, and soon going to replace `isEnabled` with the `ModBehaviour`'s built in `isActiveAndEnabled`

**Comment by ghost** [comment]
Fixed
