### ISSUE TITLE
Company of joined player won't be added to the Servers "GameWorld" 

### ISSUE THREAD

**Issue by daredloco** [software-inc-multiplayer/software-inc-multiplayer#31]
**Describe the bug**
Company of joined player won't be added to the Servers "GameWorld" 

**To Reproduce**
1) Connect to a Server

**Expected behaviour**
Should add the company to the list of companies in the Servers GameWorld

**Desktop (please complete the following information):**
 - OS: All
 - Software Inc Version All
 - Mod Version 0.2.7-unstable
 
**Additional context**
I'll try to fix the GameWorld so the Company will be added as it should

**Comment by daredloco** [comment]
Made a possible fix for this Issue, needs testing

**Comment by Datsami000** [comment]
I feel like this has taken months lol

**Comment by ghost** [comment]
No clue why its not working, i've checked the code multiple times but for now, pushing aside and fixing the long list of stuff before working on gameplay (this)

**Comment by Datsami000** [comment]
So... this means that this won't be fixed soon either? Or does it mean that it's still being fixed?

**Comment by ghost** [comment]
Its at the bottom for now.

**Comment by Datsami000** [comment]
? What does that mean?

**Comment by ghost** [comment]
At the bottom of our priorities.

**Comment by ghost** [comment]
Oops wrong button lmfao

**Comment by Datsami000** [comment]
Okay. So the New Manager and Gameplay is being worked on rather than this?

**Comment by ghost** [comment]
No, we are sorting the server out so we can easily add new network requests/features to the server. Will be doing the same to the client after the server is cleaned up.

**Comment by Datsami000** [comment]
I can't wait to see it!
