### ISSUE TITLE
Empty messages are sendable & a console error.

### ISSUE THREAD

**Issue by Datsami000** [software-inc-multiplayer/software-inc-multiplayer#42]
If you don't type anything and send a message, it sends!
*To Reproduce**
1. Open mainScene, and start a server
2. Have someone join the server
3. DON'T TYPE ANYTHING INTO CHAT BOX and click send
4. The other person on server will see the empty message

**Expected behaviour**
The message shouldn't send and a warning pops up and says, " Type before you send!"

**Screenshots**
![image](https://user-images.githubusercontent.com/69433023/92329440-7714b480-f035-11ea-8400-d727611d8641.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version: Alpha 11.6.11
 - Mod Version: 0.3.1-closed
 
**Additional context**
another error pops up in console too. Dont know how it was triggered, but it was. Image:
![image](https://user-images.githubusercontent.com/69433023/92329561-218cd780-f036-11ea-931c-7055ad322506.png)

**Comment by Chik3r** [comment]
That error might be my fault, I was changing the gamespeed through the console and got this error:
![image](https://user-images.githubusercontent.com/31808958/92329712-9fa1ac00-f03f-11ea-9d4f-c11f2dd4e783.png)

**Comment by Datsami000** [comment]
That is an error and a half.

**Comment by daredloco** [comment]
I did fix the part with the empty message, @cal3432 can you create a Popup or such for it?

https://github.com/software-inc-multiplayer/software-inc-multiplayer/commit/fcef4f3305aaa732b90e3ad66170837718840e9a
thats the commit for the fix.

The GameSpeed problem was fixed, but as we had to "go back" it came back as well. I need to see if i can find the commit where i did fix it.

**Comment by Datsami000** [comment]
What about the console error that I showed? 
![image](https://user-images.githubusercontent.com/69433023/92330202-22743800-f03b-11ea-8bb3-46b14eb3a6bd.png)

**Comment by daredloco** [comment]
Did probably fix the problem with the GameSpeed, but needs testing:
https://github.com/software-inc-multiplayer/software-inc-multiplayer/commit/3973ee7c5dea5f65ef58573582a40f0e82627441

**Comment by ghost** [comment]
This is fixed. In 0.3.2-closed which will be released soon.
