### ISSUE TITLE
Files get not copied if folder is missing

### ISSUE THREAD

**Issue by Xemrox** [software-inc-multiplayer/software-inc-multiplayer#48]
As the title says, if the folder is deleted for some reason the files do not get copied.

See:
https://github.com/software-inc-multiplayer/software-inc-multiplayer/blob/6d91a33a0bc726492ef06428b2f9d70445122c1e/Manager/pages/js/main.js#L54

**Comment by ghost** [comment]
I might just drop support of the current manager, the new manager will fix everything. For now, remake the multiplayer folder as the current manager is a pain in the ass.
