### ISSUE TITLE
Networking Replace Telepathy

### ISSUE THREAD

**Issue by Xemrox** [software-inc-multiplayer/software-inc-multiplayer#54]
Telepathy has some quircks wich we have to fix by replacing it ...

**Comment by Datsami000** [comment]
What are we going to replace it with? Are we going to make a replacement ourselves?

**Comment by daredloco** [comment]
> 
> 
> What are we going to replace it with? Are we going to make a replacement ourselves?

As far as I understood @Xemrox we do just that!
