### ISSUE TITLE
Move the multiplayer button from the mainmenu to the ActorCustomization scene

### ISSUE THREAD

**Issue by daredloco** [software-inc-multiplayer/software-inc-multiplayer#68]
As it would take an additional step from connect to gamestart it would be better to move the button (and the logic) to the ActorCustomization scene.
This would make it easier for us as we wouldn't need to have to wait for the player but could already load the gameworld as soon as its fully loaded after starting a new game.
The button should be somewhere close to the default Start button, so the user knows where he has to press to start a multiplayer game.

A good location would be somewhere here:
![somewherehere.png](https://images.zenhubusercontent.com/5f984c6d512e5530df644b4f/9f19cb67-abe1-4d7c-9d2f-7d3abd2e2de5)

**Comment by MattA-Official** [comment]
When joining a game the year and difficulty should be locked to whatever the server admin set. How would this affect that?

**Comment by MattA-Official** [comment]
Another option would be a multiplayer button in the main menu. This then opens up a window with a join and create option.

Join -> If it is a server they have joined before it opens the correct save, if it is a new server it opens the ActorCustomisation screen with some options locked.
Create -> opens the ActorCustomisation screen with extra server admin options

**Comment by Datsami000** [comment]
Wouldn't the placement conflict with the location of the "Mods" Popup?

**Comment by IMB11** [comment]
Moved to #81
