### ISSUE TITLE
System.Exception if mod is enabled.

### ISSUE THREAD

**Issue by User8426** [software-inc-multiplayer/software-inc-multiplayer#74]
**Describe the bug**
When enabling multiplayer, an error message appears in the errors section of mods. The error is as follows "System.Exception: [CS1644]: Feature 'declaration expression' cannot be used because it is not part of the C# 6.0 language specification in GameBehaviour.cs at [205 , 119]"

**To Reproduce**
Steps to reproduce the behaviour:
1. Put the Software Inc Multiplayer Mod in a DLLMods folder
2. Run Software Inc
3. Enable the mod
4. Head to errors section of mods

**Expected behaviour**
Either no error or a different error. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Software Inc Version Alpha 11.7.62
 - Mod Version Clone of master folder at 26/07/2021
 
**Additional context**
The error seems to be coming from line 205 from file GameBehavior.cs.
if (Networking.Server.isRunning)

**Comment by daredloco** [comment]
Thank you for you report!
Could you test it with the version from https://github.com/software-inc-multiplayer/software-inc-multiplayer/tree/networking-rework please.
If this won't fix the problem, please inform us so we can do further investigations about the problem, but this is the newest version and it contains a total rework of the networking code.
The master branch is from february, so it's outdated.
As soon as we're done with the rework we will update the master branch, sorry for the possible confusion.

**Comment by User8426** [comment]
Thanks for the response, I didn't realise this branch was available, I assumed the master branch would be as up to date as possible. However it appears there's a new error this time instead "Sysetm.Exception [CS1014]: A get or set accessor expected in ScrollableTextField.cs at [22,2]"
